# Generated by Django 5.0.2 on 2024-03-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0002_alter_profile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Team Leader', 'Team Leader'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Web designer', 'Web designer')], default='Frontend Developer', max_length=29),
        ),
        migrations.AlterField(
            model_name='profile',
            name='collegename',
            field=models.CharField(choices=[('Coimbatore branch', 'Coimbatore branch'), ('Chennai branch', 'Chennai branch')], max_length=29),
        ),
    ]
