# Generated by Django 5.0.2 on 2024-03-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0004_alter_complaint_type_of_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Type_of_complaint',
            field=models.CharField(choices=[('crm', 'crm'), ('blog', 'blog'), ('ecommerce', 'ecommerce'), ('billing', 'billing'), ('cms', 'cms')], max_length=200, null=True),
        ),
    ]
