# Generated by Django 5.0.2 on 2024-03-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0005_alter_complaint_type_of_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Type_of_complaint',
            field=models.CharField(choices=[('crm project', 'crm project'), ('blog project', 'blog project'), ('ecommerce project', 'ecommerce project'), ('billing project', 'billing project'), ('cms project', 'cms project')], max_length=200, null=True),
        ),
    ]
