# Generated by Django 5.0.2 on 2024-03-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0006_alter_complaint_type_of_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
