# Generated by Django 5.0.2 on 2024-03-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0007_complaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
